# Generated by Django 4.2.27 on 2026-01-30 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='branding/')),
                ('color_scheme', models.CharField(max_length=20)),
                ('welcome_message', models.TextField()),
                ('default_session_minutes', models.IntegerField(default=60)),
                ('buffer_minutes', models.IntegerField(default=15)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorBlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorinvitetoken',
            name='tutor',
        ),
        migrations.AddField(
            model_name='user',
            name='buffer_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='default_session_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TutorBranding',
        ),
        migrations.DeleteModel(
            name='TutorInviteToken',
        ),
        migrations.AddField(
            model_name='tutorblockedday',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
