# Generated by Django 4.2.27 on 2026-02-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklybooking',
            old_name='effective_start_date',
            new_name='start_date',
        ),
    ]
