# Generated by Django 4.2.27 on 2026-02-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_effective_start_date_weeklybooking_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='BookingAdhoc',
        ),
        migrations.RenameModel(
            old_name='WeeklyBooking',
            new_name='BookingWeekly',
        ),
    ]
