# Generated by Django 4.2.27 on 2026-01-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tutor_tutorblockedday_remove_tutorinvitetoken_tutor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutor',
            new_name='TutorProfile',
        ),
    ]
