# Generated by Django 4.2.27 on 2026-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_appointment_bookingadhoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
