# Generated by Django 4.2.27 on 2026-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_note_author_alter_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
