# Generated by Django 4.2.27 on 2026-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_smsconversation_smssendjob_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
