# Generated by Django 4.2.27 on 2026-03-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_studentprofile_address_studentprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
