# Generated by Django 4.2.27 on 2026-02-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='skill',
            name='grades',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
