# Generated by Django 4.2.27 on 2026-03-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_smsmessage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(blank=True, default='0493461541', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='mobile',
            field=models.CharField(blank=True, default='0493461541', max_length=20, null=True),
        ),
    ]
