# Generated by Django 4.2.27 on 2026-02-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_skill_grade_level_skill_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
