# Generated by Django 4.2.27 on 2026-03-11 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_studentprofile_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssendjob',
            name='student',
        ),
        migrations.RemoveField(
            model_name='smssendjob',
            name='tutor',
        ),
        migrations.AddField(
            model_name='smssendjob',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='backend.smsconversation'),
        ),
        migrations.AddField(
            model_name='smssendjob',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smssendjob',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smssendjob',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
