# Generated by Django 4.2.27 on 2026-02-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_template_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='selected_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_taken_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
