# Generated by Django 4.2.27 on 2026-02-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_question_correct_question_selected_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
