# Generated by Django 4.2.27 on 2026-02-20 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_weeklybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybooking',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_tutor_weekly', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklybooking',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_weekly', to=settings.AUTH_USER_MODEL),
        ),
    ]
